GET http://localhost:8080/api/employees HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/employees/?officeCode=19 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/employees/1134 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/auth/dmurphy@classicmodelcars.com HTTP/1.1
content-type: application/json
###

POST http://localhost:8080/api/employees HTTP/1.1
content-type: application/json

{
  "lastName": "Nishi",
  "firstName": "Mami",
  "extension": "x101",
  "email": "mnishi@classicmodelcars.com",
  "officeCode": "5",
  "manager": "3",
  "jobTitle": "Sales Rep"
}

###

PUT http://localhost:8080/api/employees/11 HTTP/1.1
content-type: application/json

{
  "lastName": "Nishi",
  "firstName": "Mami",
  "extension": "x101",
  "email": "mnishi@classicmodelcars.com",
  "officeCode": "6",
  "manager": "3",
  "jobTitle": "Sales Rep"
}


###

DELETE  http://localhost:8080/api/employees/1435 HTTP/1.1
content-type: application/json
